### ISSUE TITLE
Training data size

### ISSUE THREAD

**Issue by EternityZY** [LilJing/causal_hmm#1]
Hello, can you provide the original sample size of the data? I want to generate some random numbers so that the program can run

**Comment by LilJing** [comment]
> Hello, can you provide the original sample size of the data? I want to generate some random numbers so that the program can run

**Comment by LilJing** [comment]
> Hello, can you provide the original sample size of the data? I want to generate some random numbers so that the program can run

Hi, the original sample size is 128 X 128 with three rgb channels.
